// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDq0Fpp2i8Wq4MvFzKS1kmVhsZTpB0Mli4',
    appId: '1:601212857943:android:fc013cf558ee107742fd12',
    messagingSenderId: '601212857943',
    projectId: 'my-ledger-76727',
    storageBucket: 'my-ledger-76727.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDzAdoHn2rJhawvwq4U774WRD1E4uJqXts',
    appId: '1:601212857943:ios:491648084bcbe87c42fd12',
    messagingSenderId: '601212857943',
    projectId: 'my-ledger-76727',
    storageBucket: 'my-ledger-76727.appspot.com',
    androidClientId: '601212857943-dhdur7ounk5f36dn5kifmd5pfbk97g7b.apps.googleusercontent.com',
    iosClientId: '601212857943-s59c17in1qvlj7fb0bjvbfl02c7e7od5.apps.googleusercontent.com',
    iosBundleId: 'com.example.accomodationApp',
  );
}
